// Lista dei reati penali italiani per i suggerimenti
export const REATI_PENALI = [
    'omicidio',
    'omicidio preterintenzionale',
    'omicidio colposo',
    'lesioni personali',
    'lesioni gravi',
    'lesioni gravissime',
    'percosse',
    'violenza privata',
    'minaccia',
    'estorsione',
    'rapina',
    'furto',
    'furto aggravato',
    'furto con strappo',
    'furto in abitazione',
    'furto d\'auto',
    'furto di moto',
    'furto di bicicletta',
    'furto di documenti',
    'furto di identità',
    'truffa',
    'appropriazione indebita',
    'ricettazione',
    'riciclaggio',
    'usura',
    'usura aggravata',
    'associazione per delinquere',
    'associazione mafiosa',
    'concorso in associazione mafiosa',
    'concorso esterno in associazione mafiosa',
    'estorsione aggravata',
    'sequestro di persona',
    'sequestro di persona a scopo di estorsione',
    'violenza sessuale',
    'violenza sessuale aggravata',
    'atti sessuali con minorenne',
    'corruzione',
    'corruzione in atti giudiziari',
    'corruzione per un atto contrario ai doveri d\'ufficio',
    'corruzione per un atto conforme ai doveri d\'ufficio',
    'concussione',
    'abuso d\'ufficio',
    'peculato',
    'peculato mediante profitto',
    'peculato mediante uso',
    'malversazione',
    'falso in atto pubblico',
    'falso in scrittura privata',
    'falso ideologico',
    'falso materiale',
    'soppressione di atti',
    'soppressione di documenti',
    'soppressione di prove',
    'calunnia',
    'diffamazione',
    'ingiuria',
    'minaccia o violenza a pubblico ufficiale',
    'resistenza a pubblico ufficiale',
    'oltraggio a pubblico ufficiale',
    'violazione di domicilio',
    'violazione di domicilio con violenza',
    'interruzione di pubblico servizio',
    'interruzione di pubblico servizio con violenza',
    'interruzione di pubblico servizio con minaccia',
    'interruzione di pubblico servizio con inganno',
    'interruzione di pubblico servizio con abuso di autorità',
    'interruzione di pubblico servizio con abuso di ufficio',
    'interruzione di pubblico servizio con abuso di potere',
    'interruzione di pubblico servizio con abuso di posizione',
    'interruzione di pubblico servizio con abuso di funzione',
    'interruzione di pubblico servizio con abuso di competenza',
    'interruzione di pubblico servizio con abuso di giurisdizione',
    'interruzione di pubblico servizio con abuso di amministrazione',
    'interruzione di pubblico servizio con abuso di gestione',
    'interruzione di pubblico servizio con abuso di direzione',
    'interruzione di pubblico servizio con abuso di controllo',
    'interruzione di pubblico servizio con abuso di vigilanza',
    'interruzione di pubblico servizio con abuso di sorveglianza',
    'interruzione di pubblico servizio con abuso di custodia',
    'interruzione di pubblico servizio con abuso di protezione',
    'interruzione di pubblico servizio con abuso di difesa',
    'interruzione di pubblico servizio con abuso di tutela',
    'interruzione di pubblico servizio con abuso di garanzia',
    'interruzione di pubblico servizio con abuso di sicurezza',
    'interruzione di pubblico servizio con abuso di ordine',
    'interruzione di pubblico servizio con abuso di disciplina',
    'interruzione di pubblico servizio con abuso di regolamento',
    'interruzione di pubblico servizio con abuso di procedura',
    'interruzione di pubblico servizio con abuso di protocollo',
    'interruzione di pubblico servizio con abuso di formalità',
    'interruzione di pubblico servizio con abuso di ritualità',
    'interruzione di pubblico servizio con abuso di cerimoniale',
    'interruzione di pubblico servizio con abuso di etichetta',
    'interruzione di pubblico servizio con abuso di convenzione',
    'interruzione di pubblico servizio con abuso di accordo',
    'interruzione di pubblico servizio con abuso di patto',
    'interruzione di pubblico servizio con abuso di contratto',
    'interruzione di pubblico servizio con abuso di convenzione',
    'interruzione di pubblico servizio con abuso di accordo',
    'interruzione di pubblico servizio con abuso di patto',
    'interruzione di pubblico servizio con abuso di contratto'
]

export const getReatoSuggestions = (query: string): string[] => {
    if (!query || query.length < 2) return []

    const normalizedQuery = query.toLowerCase().trim()
    return REATI_PENALI
        .filter(reato => reato.toLowerCase().includes(normalizedQuery))
        .slice(0, 10) // Limita a 10 suggerimenti
}

export const isReatoValid = (reato: string): boolean => {
    return REATI_PENALI.includes(reato.toLowerCase())
}
